import { Business } from './types';

export const MOCK_BUSINESSES: Business[] = [
    {
        id: '1',
        name: 'Snack Bar O Tachinho',
        category: 'Restaurant / Snack',
        address: 'Campo de Ourique, Lisbon',
        website: undefined,
        rating: 0,
        reviewCount: 5, // Estimated < 10
        hasOwnerPhotos: false,
        isClaimed: false,
        hoursListed: true,
        phoneListed: true,
        issues: ['No Website', 'Very few reviews', 'Low visibility'],
        leadScore: 70,
        priority: 'HIGH',
        outreachPitch: "Olá! Sou vizinho aqui de Campo de Ourique e reparei que o 'O Tachinho' tem uma comida fantástica mas é difícil de encontrar online — tem pouquíssimas avaliações no Google. Eu tenho um sistema simples que ajuda muito a trazer mais gente. Posso mostrar-lhe como funciona em 2 minutos?",
        googleMapsRank: 15
    },
    {
        id: '2',
        name: 'Caffè Bar Garibaldi',
        category: 'Italian Café',
        address: 'Rua Ferreira Borges 30A',
        website: undefined,
        rating: 4.5,
        reviewCount: 50,
        hasOwnerPhotos: true,
        isClaimed: true,
        hoursListed: true,
        phoneListed: true,
        issues: ['No Website (Facebook only)', 'Missed SEO opportunity'],
        leadScore: 55,
        priority: 'MEDIUM',
        outreachPitch: "Olá! Sou fã do vosso conceito italiano aqui no bairro. Reparei que não têm site próprio, só o Facebook, e isso pode dificultar quem procura pelo Google Maps. Eu ajudo negócios locais a otimizar o perfil Google e a conseguir mais reviews automaticamente. Gostariam de ver uma demo sem compromisso?",
        googleMapsRank: 8
    },
    {
        id: '3',
        name: 'Imperial de Campo de Ourique',
        category: 'Restaurant',
        address: 'R. Correia Teles 67',
        website: undefined,
        rating: 4.6,
        reviewCount: 1200,
        hasOwnerPhotos: false,
        isClaimed: true,
        hoursListed: true,
        phoneListed: true,
        issues: ['No Website', 'No reservations system link'],
        leadScore: 45,
        priority: 'MEDIUM',
        outreachPitch: "Boa tarde! O Imperial é uma instituição aqui no bairro, mas reparei que não têm site próprio linkado no Google, o que é uma pena para os turistas que procuram onde comer. O meu trabalho é garantir que casas com esta qualidade têm a nota que merecem (4.8+). Tenho uma solução simples para aumentar reviews.",
        googleMapsRank: 1
    },
    {
        id: '4',
        name: 'A Tentadora',
        category: 'Pastelaria',
        address: 'Rua Ferreira Borges 1',
        website: 'atentadora.shop',
        rating: 4.2,
        reviewCount: 848,
        hasOwnerPhotos: true,
        isClaimed: true,
        hoursListed: true,
        phoneListed: true,
        issues: ['Website is basic', 'Could optimize descriptions'],
        leadScore: 35,
        priority: 'LOW',
        outreachPitch: "Hi! I noticed your GMB profile is strong, but there are a few advanced optimization tricks (like 'Updates' and Q&A) that could drive even more foot traffic. Happy to share a free audit.",
        googleMapsRank: 2
    },
    {
        id: '5',
        name: 'Jeronymo Café',
        category: 'Café',
        address: 'Campo de Ourique',
        website: 'jeronymo.pt',
        rating: 4.2,
        reviewCount: 668,
        hasOwnerPhotos: true,
        isClaimed: true,
        hoursListed: true,
        phoneListed: true,
        issues: [],
        leadScore: 20,
        priority: 'LOW',
        outreachPitch: "N/A",
        googleMapsRank: 3
    }
];
